### ISSUE TITLE
Chrom's portrait for both directions

### ISSUE THREAD

**Issue by BreakinBenny** [robotortoise/FEFTS#8]
Chrom has sprites for facing both the left and right in both Awakening and Fates, but in this Text Simulator he doesn't have that because the two sprites have an identical English name.

**Comment by robotortoise** [comment]
Fixed a few things in your branch, and now it works.

Thanks for your help!

**Comment by BreakinBenny** [comment]
Weee! Thanks Rob, now this can go on Fire Emblem Wiki in no time...!

Hold on, damnit the Portrait Generator refuses to open and prompts an error!
