### ISSUE TITLE
Portrait Generator crashes upon trying to open it

### ISSUE THREAD

**Issue by BreakinBenny** [robotortoise/FEFTS#9]
The newest version now crashes the application if you try opening the Portrait Generator. Why?

**Comment by robotortoise** [comment]
It wasn't actually a coding error. It was a compiling error.

Can't tell you what; I've compiled this revision on my laptop. I updated the latest binary with a fixed version.

**Comment by BreakinBenny** [comment]
...Yay, looks like I won't be able to extract Chrom's right-face portrait in a loooong time.

**Comment by robotortoise** [comment]
Like I said, I'm not a coder. I don't know how to add portraits.

If you want the sprites, just search for "クロム" in the /Resources/images/face folder.
